# Generated by Django 5.0.2 on 2026-06-24 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kudos',
            options={'verbose_name_plural': 'Kudos'},
        ),
    ]
